<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\CountryTranslation;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        // Each entry: ['iso_alpha2', 'country_code', 'translations' => [locale => name]]
        // Only the locales explicitly listed here are seeded — no fallback, no auto-fill
        // for locales added later. Those must be added manually to each entry.
        $countries = [
            ['iso_alpha2' => 'AF', 'country_code' => '+93',    'translations' => ['pt-PT' => 'Afeganistão',                       'en-UK' => 'Afghanistan']],
            ['iso_alpha2' => 'AL', 'country_code' => '+355',   'translations' => ['pt-PT' => 'Albânia',                           'en-UK' => 'Albania']],
            ['iso_alpha2' => 'DZ', 'country_code' => '+213',   'translations' => ['pt-PT' => 'Argélia',                           'en-UK' => 'Algeria']],
            ['iso_alpha2' => 'AD', 'country_code' => '+376',   'translations' => ['pt-PT' => 'Andorra',                           'en-UK' => 'Andorra']],
            ['iso_alpha2' => 'AO', 'country_code' => '+244',   'translations' => ['pt-PT' => 'Angola',                            'en-UK' => 'Angola']],
            ['iso_alpha2' => 'AG', 'country_code' => '+1-268', 'translations' => ['pt-PT' => 'Antígua e Barbuda',                 'en-UK' => 'Antigua and Barbuda']],
            ['iso_alpha2' => 'AR', 'country_code' => '+54',    'translations' => ['pt-PT' => 'Argentina',                         'en-UK' => 'Argentina']],
            ['iso_alpha2' => 'AM', 'country_code' => '+374',   'translations' => ['pt-PT' => 'Arménia',                           'en-UK' => 'Armenia']],
            ['iso_alpha2' => 'AU', 'country_code' => '+61',    'translations' => ['pt-PT' => 'Austrália',                         'en-UK' => 'Australia']],
            ['iso_alpha2' => 'AT', 'country_code' => '+43',    'translations' => ['pt-PT' => 'Áustria',                           'en-UK' => 'Austria']],
            ['iso_alpha2' => 'AZ', 'country_code' => '+994',   'translations' => ['pt-PT' => 'Azerbaijão',                        'en-UK' => 'Azerbaijan']],
            ['iso_alpha2' => 'BS', 'country_code' => '+1-242', 'translations' => ['pt-PT' => 'Bahamas',                           'en-UK' => 'Bahamas']],
            ['iso_alpha2' => 'BH', 'country_code' => '+973',   'translations' => ['pt-PT' => 'Bahrein',                           'en-UK' => 'Bahrain']],
            ['iso_alpha2' => 'BD', 'country_code' => '+880',   'translations' => ['pt-PT' => 'Bangladesh',                        'en-UK' => 'Bangladesh']],
            ['iso_alpha2' => 'BB', 'country_code' => '+1-246', 'translations' => ['pt-PT' => 'Barbados',                          'en-UK' => 'Barbados']],
            ['iso_alpha2' => 'BY', 'country_code' => '+375',   'translations' => ['pt-PT' => 'Bielorrússia',                      'en-UK' => 'Belarus']],
            ['iso_alpha2' => 'BE', 'country_code' => '+32',    'translations' => ['pt-PT' => 'Bélgica',                           'en-UK' => 'Belgium']],
            ['iso_alpha2' => 'BZ', 'country_code' => '+501',   'translations' => ['pt-PT' => 'Belize',                            'en-UK' => 'Belize']],
            ['iso_alpha2' => 'BJ', 'country_code' => '+229',   'translations' => ['pt-PT' => 'Benim',                             'en-UK' => 'Benin']],
            ['iso_alpha2' => 'BT', 'country_code' => '+975',   'translations' => ['pt-PT' => 'Butão',                             'en-UK' => 'Bhutan']],
            ['iso_alpha2' => 'BO', 'country_code' => '+591',   'translations' => ['pt-PT' => 'Bolívia',                           'en-UK' => 'Bolivia']],
            ['iso_alpha2' => 'BA', 'country_code' => '+387',   'translations' => ['pt-PT' => 'Bósnia e Herzegovina',              'en-UK' => 'Bosnia and Herzegovina']],
            ['iso_alpha2' => 'BW', 'country_code' => '+267',   'translations' => ['pt-PT' => 'Botswana',                          'en-UK' => 'Botswana']],
            ['iso_alpha2' => 'BR', 'country_code' => '+55',    'translations' => ['pt-PT' => 'Brasil',                            'en-UK' => 'Brazil']],
            ['iso_alpha2' => 'BN', 'country_code' => '+673',   'translations' => ['pt-PT' => 'Brunei',                            'en-UK' => 'Brunei']],
            ['iso_alpha2' => 'BG', 'country_code' => '+359',   'translations' => ['pt-PT' => 'Bulgária',                          'en-UK' => 'Bulgaria']],
            ['iso_alpha2' => 'BF', 'country_code' => '+226',   'translations' => ['pt-PT' => 'Burkina Faso',                      'en-UK' => 'Burkina Faso']],
            ['iso_alpha2' => 'BI', 'country_code' => '+257',   'translations' => ['pt-PT' => 'Burundi',                           'en-UK' => 'Burundi']],
            ['iso_alpha2' => 'CV', 'country_code' => '+238',   'translations' => ['pt-PT' => 'Cabo Verde',                        'en-UK' => 'Cabo Verde']],
            ['iso_alpha2' => 'KH', 'country_code' => '+855',   'translations' => ['pt-PT' => 'Camboja',                           'en-UK' => 'Cambodia']],
            ['iso_alpha2' => 'CM', 'country_code' => '+237',   'translations' => ['pt-PT' => 'Camarões',                          'en-UK' => 'Cameroon']],
            ['iso_alpha2' => 'CA', 'country_code' => '+1',     'translations' => ['pt-PT' => 'Canadá',                            'en-UK' => 'Canada']],
            ['iso_alpha2' => 'CF', 'country_code' => '+236',   'translations' => ['pt-PT' => 'República Centro-Africana',         'en-UK' => 'Central African Republic']],
            ['iso_alpha2' => 'TD', 'country_code' => '+235',   'translations' => ['pt-PT' => 'Chade',                             'en-UK' => 'Chad']],
            ['iso_alpha2' => 'CL', 'country_code' => '+56',    'translations' => ['pt-PT' => 'Chile',                             'en-UK' => 'Chile']],
            ['iso_alpha2' => 'CN', 'country_code' => '+86',    'translations' => ['pt-PT' => 'China',                             'en-UK' => 'China']],
            ['iso_alpha2' => 'CO', 'country_code' => '+57',    'translations' => ['pt-PT' => 'Colômbia',                          'en-UK' => 'Colombia']],
            ['iso_alpha2' => 'KM', 'country_code' => '+269',   'translations' => ['pt-PT' => 'Comores',                           'en-UK' => 'Comoros']],
            ['iso_alpha2' => 'CG', 'country_code' => '+242',   'translations' => ['pt-PT' => 'Congo',                             'en-UK' => 'Congo']],
            ['iso_alpha2' => 'CD', 'country_code' => '+243',   'translations' => ['pt-PT' => 'República Democrática do Congo',    'en-UK' => 'Congo (DRC)']],
            ['iso_alpha2' => 'CR', 'country_code' => '+506',   'translations' => ['pt-PT' => 'Costa Rica',                        'en-UK' => 'Costa Rica']],
            ['iso_alpha2' => 'CI', 'country_code' => '+225',   'translations' => ['pt-PT' => 'Costa do Marfim',                   'en-UK' => "Côte d'Ivoire"]],
            ['iso_alpha2' => 'HR', 'country_code' => '+385',   'translations' => ['pt-PT' => 'Croácia',                           'en-UK' => 'Croatia']],
            ['iso_alpha2' => 'CU', 'country_code' => '+53',    'translations' => ['pt-PT' => 'Cuba',                              'en-UK' => 'Cuba']],
            ['iso_alpha2' => 'CY', 'country_code' => '+357',   'translations' => ['pt-PT' => 'Chipre',                            'en-UK' => 'Cyprus']],
            ['iso_alpha2' => 'CZ', 'country_code' => '+420',   'translations' => ['pt-PT' => 'Chéquia',                           'en-UK' => 'Czech Republic']],
            ['iso_alpha2' => 'DK', 'country_code' => '+45',    'translations' => ['pt-PT' => 'Dinamarca',                         'en-UK' => 'Denmark']],
            ['iso_alpha2' => 'DJ', 'country_code' => '+253',   'translations' => ['pt-PT' => 'Djibouti',                          'en-UK' => 'Djibouti']],
            ['iso_alpha2' => 'DM', 'country_code' => '+1-767', 'translations' => ['pt-PT' => 'Dominica',                          'en-UK' => 'Dominica']],
            ['iso_alpha2' => 'DO', 'country_code' => '+1-809', 'translations' => ['pt-PT' => 'República Dominicana',              'en-UK' => 'Dominican Republic']],
            ['iso_alpha2' => 'EC', 'country_code' => '+593',   'translations' => ['pt-PT' => 'Equador',                           'en-UK' => 'Ecuador']],
            ['iso_alpha2' => 'EG', 'country_code' => '+20',    'translations' => ['pt-PT' => 'Egito',                             'en-UK' => 'Egypt']],
            ['iso_alpha2' => 'SV', 'country_code' => '+503',   'translations' => ['pt-PT' => 'El Salvador',                       'en-UK' => 'El Salvador']],
            ['iso_alpha2' => 'GQ', 'country_code' => '+240',   'translations' => ['pt-PT' => 'Guiné Equatorial',                  'en-UK' => 'Equatorial Guinea']],
            ['iso_alpha2' => 'ER', 'country_code' => '+291',   'translations' => ['pt-PT' => 'Eritreia',                          'en-UK' => 'Eritrea']],
            ['iso_alpha2' => 'EE', 'country_code' => '+372',   'translations' => ['pt-PT' => 'Estónia',                           'en-UK' => 'Estonia']],
            ['iso_alpha2' => 'SZ', 'country_code' => '+268',   'translations' => ['pt-PT' => 'Eswatini',                          'en-UK' => 'Eswatini']],
            ['iso_alpha2' => 'ET', 'country_code' => '+251',   'translations' => ['pt-PT' => 'Etiópia',                           'en-UK' => 'Ethiopia']],
            ['iso_alpha2' => 'FJ', 'country_code' => '+679',   'translations' => ['pt-PT' => 'Fiji',                              'en-UK' => 'Fiji']],
            ['iso_alpha2' => 'FI', 'country_code' => '+358',   'translations' => ['pt-PT' => 'Finlândia',                         'en-UK' => 'Finland']],
            ['iso_alpha2' => 'FR', 'country_code' => '+33',    'translations' => ['pt-PT' => 'França',                            'en-UK' => 'France']],
            ['iso_alpha2' => 'GA', 'country_code' => '+241',   'translations' => ['pt-PT' => 'Gabão',                             'en-UK' => 'Gabon']],
            ['iso_alpha2' => 'GM', 'country_code' => '+220',   'translations' => ['pt-PT' => 'Gâmbia',                            'en-UK' => 'Gambia']],
            ['iso_alpha2' => 'GE', 'country_code' => '+995',   'translations' => ['pt-PT' => 'Geórgia',                           'en-UK' => 'Georgia']],
            ['iso_alpha2' => 'DE', 'country_code' => '+49',    'translations' => ['pt-PT' => 'Alemanha',                          'en-UK' => 'Germany']],
            ['iso_alpha2' => 'GH', 'country_code' => '+233',   'translations' => ['pt-PT' => 'Gana',                              'en-UK' => 'Ghana']],
            ['iso_alpha2' => 'GR', 'country_code' => '+30',    'translations' => ['pt-PT' => 'Grécia',                            'en-UK' => 'Greece']],
            ['iso_alpha2' => 'GD', 'country_code' => '+1-473', 'translations' => ['pt-PT' => 'Granada',                           'en-UK' => 'Grenada']],
            ['iso_alpha2' => 'GT', 'country_code' => '+502',   'translations' => ['pt-PT' => 'Guatemala',                         'en-UK' => 'Guatemala']],
            ['iso_alpha2' => 'GN', 'country_code' => '+224',   'translations' => ['pt-PT' => 'Guiné',                             'en-UK' => 'Guinea']],
            ['iso_alpha2' => 'GW', 'country_code' => '+245',   'translations' => ['pt-PT' => 'Guiné-Bissau',                      'en-UK' => 'Guinea-Bissau']],
            ['iso_alpha2' => 'GY', 'country_code' => '+592',   'translations' => ['pt-PT' => 'Guiana',                            'en-UK' => 'Guyana']],
            ['iso_alpha2' => 'HT', 'country_code' => '+509',   'translations' => ['pt-PT' => 'Haiti',                             'en-UK' => 'Haiti']],
            ['iso_alpha2' => 'HN', 'country_code' => '+504',   'translations' => ['pt-PT' => 'Honduras',                          'en-UK' => 'Honduras']],
            ['iso_alpha2' => 'HU', 'country_code' => '+36',    'translations' => ['pt-PT' => 'Hungria',                           'en-UK' => 'Hungary']],
            ['iso_alpha2' => 'IS', 'country_code' => '+354',   'translations' => ['pt-PT' => 'Islândia',                          'en-UK' => 'Iceland']],
            ['iso_alpha2' => 'IN', 'country_code' => '+91',    'translations' => ['pt-PT' => 'Índia',                             'en-UK' => 'India']],
            ['iso_alpha2' => 'ID', 'country_code' => '+62',    'translations' => ['pt-PT' => 'Indonésia',                         'en-UK' => 'Indonesia']],
            ['iso_alpha2' => 'IR', 'country_code' => '+98',    'translations' => ['pt-PT' => 'Irão',                              'en-UK' => 'Iran']],
            ['iso_alpha2' => 'IQ', 'country_code' => '+964',   'translations' => ['pt-PT' => 'Iraque',                            'en-UK' => 'Iraq']],
            ['iso_alpha2' => 'IE', 'country_code' => '+353',   'translations' => ['pt-PT' => 'Irlanda',                           'en-UK' => 'Ireland']],
            ['iso_alpha2' => 'IL', 'country_code' => '+972',   'translations' => ['pt-PT' => 'Israel',                            'en-UK' => 'Israel']],
            ['iso_alpha2' => 'IT', 'country_code' => '+39',    'translations' => ['pt-PT' => 'Itália',                            'en-UK' => 'Italy']],
            ['iso_alpha2' => 'JM', 'country_code' => '+1-876', 'translations' => ['pt-PT' => 'Jamaica',                           'en-UK' => 'Jamaica']],
            ['iso_alpha2' => 'JP', 'country_code' => '+81',    'translations' => ['pt-PT' => 'Japão',                             'en-UK' => 'Japan']],
            ['iso_alpha2' => 'JO', 'country_code' => '+962',   'translations' => ['pt-PT' => 'Jordânia',                          'en-UK' => 'Jordan']],
            ['iso_alpha2' => 'KZ', 'country_code' => '+7',     'translations' => ['pt-PT' => 'Cazaquistão',                       'en-UK' => 'Kazakhstan']],
            ['iso_alpha2' => 'KE', 'country_code' => '+254',   'translations' => ['pt-PT' => 'Quénia',                            'en-UK' => 'Kenya']],
            ['iso_alpha2' => 'KI', 'country_code' => '+686',   'translations' => ['pt-PT' => 'Kiribati',                          'en-UK' => 'Kiribati']],
            ['iso_alpha2' => 'KP', 'country_code' => '+850',   'translations' => ['pt-PT' => 'Coreia do Norte',                   'en-UK' => 'Korea (North)']],
            ['iso_alpha2' => 'KR', 'country_code' => '+82',    'translations' => ['pt-PT' => 'Coreia do Sul',                     'en-UK' => 'Korea (South)']],
            ['iso_alpha2' => 'XK', 'country_code' => '+383',   'translations' => ['pt-PT' => 'Kosovo',                            'en-UK' => 'Kosovo']],
            ['iso_alpha2' => 'KW', 'country_code' => '+965',   'translations' => ['pt-PT' => 'Kuwait',                            'en-UK' => 'Kuwait']],
            ['iso_alpha2' => 'KG', 'country_code' => '+996',   'translations' => ['pt-PT' => 'Quirguistão',                       'en-UK' => 'Kyrgyzstan']],
            ['iso_alpha2' => 'LA', 'country_code' => '+856',   'translations' => ['pt-PT' => 'Laos',                              'en-UK' => 'Laos']],
            ['iso_alpha2' => 'LV', 'country_code' => '+371',   'translations' => ['pt-PT' => 'Letónia',                           'en-UK' => 'Latvia']],
            ['iso_alpha2' => 'LB', 'country_code' => '+961',   'translations' => ['pt-PT' => 'Líbano',                            'en-UK' => 'Lebanon']],
            ['iso_alpha2' => 'LS', 'country_code' => '+266',   'translations' => ['pt-PT' => 'Lesoto',                            'en-UK' => 'Lesotho']],
            ['iso_alpha2' => 'LR', 'country_code' => '+231',   'translations' => ['pt-PT' => 'Libéria',                           'en-UK' => 'Liberia']],
            ['iso_alpha2' => 'LY', 'country_code' => '+218',   'translations' => ['pt-PT' => 'Líbia',                             'en-UK' => 'Libya']],
            ['iso_alpha2' => 'LI', 'country_code' => '+423',   'translations' => ['pt-PT' => 'Liechtenstein',                     'en-UK' => 'Liechtenstein']],
            ['iso_alpha2' => 'LT', 'country_code' => '+370',   'translations' => ['pt-PT' => 'Lituânia',                          'en-UK' => 'Lithuania']],
            ['iso_alpha2' => 'LU', 'country_code' => '+352',   'translations' => ['pt-PT' => 'Luxemburgo',                        'en-UK' => 'Luxembourg']],
            ['iso_alpha2' => 'MG', 'country_code' => '+261',   'translations' => ['pt-PT' => 'Madagáscar',                        'en-UK' => 'Madagascar']],
            ['iso_alpha2' => 'MW', 'country_code' => '+265',   'translations' => ['pt-PT' => 'Malawi',                            'en-UK' => 'Malawi']],
            ['iso_alpha2' => 'MY', 'country_code' => '+60',    'translations' => ['pt-PT' => 'Malásia',                           'en-UK' => 'Malaysia']],
            ['iso_alpha2' => 'MV', 'country_code' => '+960',   'translations' => ['pt-PT' => 'Maldivas',                          'en-UK' => 'Maldives']],
            ['iso_alpha2' => 'ML', 'country_code' => '+223',   'translations' => ['pt-PT' => 'Mali',                              'en-UK' => 'Mali']],
            ['iso_alpha2' => 'MT', 'country_code' => '+356',   'translations' => ['pt-PT' => 'Malta',                             'en-UK' => 'Malta']],
            ['iso_alpha2' => 'MH', 'country_code' => '+692',   'translations' => ['pt-PT' => 'Ilhas Marshall',                    'en-UK' => 'Marshall Islands']],
            ['iso_alpha2' => 'MR', 'country_code' => '+222',   'translations' => ['pt-PT' => 'Mauritânia',                        'en-UK' => 'Mauritania']],
            ['iso_alpha2' => 'MU', 'country_code' => '+230',   'translations' => ['pt-PT' => 'Maurícia',                          'en-UK' => 'Mauritius']],
            ['iso_alpha2' => 'MX', 'country_code' => '+52',    'translations' => ['pt-PT' => 'México',                            'en-UK' => 'Mexico']],
            ['iso_alpha2' => 'FM', 'country_code' => '+691',   'translations' => ['pt-PT' => 'Micronésia',                        'en-UK' => 'Micronesia']],
            ['iso_alpha2' => 'MD', 'country_code' => '+373',   'translations' => ['pt-PT' => 'Moldávia',                          'en-UK' => 'Moldova']],
            ['iso_alpha2' => 'MC', 'country_code' => '+377',   'translations' => ['pt-PT' => 'Mónaco',                            'en-UK' => 'Monaco']],
            ['iso_alpha2' => 'MN', 'country_code' => '+976',   'translations' => ['pt-PT' => 'Mongólia',                          'en-UK' => 'Mongolia']],
            ['iso_alpha2' => 'ME', 'country_code' => '+382',   'translations' => ['pt-PT' => 'Montenegro',                        'en-UK' => 'Montenegro']],
            ['iso_alpha2' => 'MA', 'country_code' => '+212',   'translations' => ['pt-PT' => 'Marrocos',                          'en-UK' => 'Morocco']],
            ['iso_alpha2' => 'MZ', 'country_code' => '+258',   'translations' => ['pt-PT' => 'Moçambique',                        'en-UK' => 'Mozambique']],
            ['iso_alpha2' => 'MM', 'country_code' => '+95',    'translations' => ['pt-PT' => 'Myanmar',                           'en-UK' => 'Myanmar']],
            ['iso_alpha2' => 'NA', 'country_code' => '+264',   'translations' => ['pt-PT' => 'Namíbia',                           'en-UK' => 'Namibia']],
            ['iso_alpha2' => 'NR', 'country_code' => '+674',   'translations' => ['pt-PT' => 'Nauru',                             'en-UK' => 'Nauru']],
            ['iso_alpha2' => 'NP', 'country_code' => '+977',   'translations' => ['pt-PT' => 'Nepal',                             'en-UK' => 'Nepal']],
            ['iso_alpha2' => 'NL', 'country_code' => '+31',    'translations' => ['pt-PT' => 'Países Baixos',                     'en-UK' => 'Netherlands']],
            ['iso_alpha2' => 'NZ', 'country_code' => '+64',    'translations' => ['pt-PT' => 'Nova Zelândia',                     'en-UK' => 'New Zealand']],
            ['iso_alpha2' => 'NI', 'country_code' => '+505',   'translations' => ['pt-PT' => 'Nicarágua',                         'en-UK' => 'Nicaragua']],
            ['iso_alpha2' => 'NE', 'country_code' => '+227',   'translations' => ['pt-PT' => 'Níger',                             'en-UK' => 'Niger']],
            ['iso_alpha2' => 'NG', 'country_code' => '+234',   'translations' => ['pt-PT' => 'Nigéria',                           'en-UK' => 'Nigeria']],
            ['iso_alpha2' => 'MK', 'country_code' => '+389',   'translations' => ['pt-PT' => 'Macedónia do Norte',                'en-UK' => 'North Macedonia']],
            ['iso_alpha2' => 'NO', 'country_code' => '+47',    'translations' => ['pt-PT' => 'Noruega',                           'en-UK' => 'Norway']],
            ['iso_alpha2' => 'OM', 'country_code' => '+968',   'translations' => ['pt-PT' => 'Omã',                               'en-UK' => 'Oman']],
            ['iso_alpha2' => 'PK', 'country_code' => '+92',    'translations' => ['pt-PT' => 'Paquistão',                         'en-UK' => 'Pakistan']],
            ['iso_alpha2' => 'PW', 'country_code' => '+680',   'translations' => ['pt-PT' => 'Palau',                             'en-UK' => 'Palau']],
            ['iso_alpha2' => 'PS', 'country_code' => '+970',   'translations' => ['pt-PT' => 'Palestina',                         'en-UK' => 'Palestine']],
            ['iso_alpha2' => 'PA', 'country_code' => '+507',   'translations' => ['pt-PT' => 'Panamá',                            'en-UK' => 'Panama']],
            ['iso_alpha2' => 'PG', 'country_code' => '+675',   'translations' => ['pt-PT' => 'Papua-Nova Guiné',                  'en-UK' => 'Papua New Guinea']],
            ['iso_alpha2' => 'PY', 'country_code' => '+595',   'translations' => ['pt-PT' => 'Paraguai',                          'en-UK' => 'Paraguay']],
            ['iso_alpha2' => 'PE', 'country_code' => '+51',    'translations' => ['pt-PT' => 'Peru',                              'en-UK' => 'Peru']],
            ['iso_alpha2' => 'PH', 'country_code' => '+63',    'translations' => ['pt-PT' => 'Filipinas',                         'en-UK' => 'Philippines']],
            ['iso_alpha2' => 'PL', 'country_code' => '+48',    'translations' => ['pt-PT' => 'Polónia',                           'en-UK' => 'Poland']],
            ['iso_alpha2' => 'PT', 'country_code' => '+351',   'translations' => ['pt-PT' => 'Portugal',                          'en-UK' => 'Portugal']],
            ['iso_alpha2' => 'QA', 'country_code' => '+974',   'translations' => ['pt-PT' => 'Qatar',                             'en-UK' => 'Qatar']],
            ['iso_alpha2' => 'RO', 'country_code' => '+40',    'translations' => ['pt-PT' => 'Roménia',                           'en-UK' => 'Romania']],
            ['iso_alpha2' => 'RU', 'country_code' => '+7',     'translations' => ['pt-PT' => 'Rússia',                            'en-UK' => 'Russia']],
            ['iso_alpha2' => 'RW', 'country_code' => '+250',   'translations' => ['pt-PT' => 'Ruanda',                            'en-UK' => 'Rwanda']],
            ['iso_alpha2' => 'KN', 'country_code' => '+1-869', 'translations' => ['pt-PT' => 'São Cristóvão e Neves',             'en-UK' => 'Saint Kitts and Nevis']],
            ['iso_alpha2' => 'LC', 'country_code' => '+1-758', 'translations' => ['pt-PT' => 'Santa Lúcia',                       'en-UK' => 'Saint Lucia']],
            ['iso_alpha2' => 'VC', 'country_code' => '+1-784', 'translations' => ['pt-PT' => 'São Vicente e Granadinas',          'en-UK' => 'Saint Vincent and the Grenadines']],
            ['iso_alpha2' => 'WS', 'country_code' => '+685',   'translations' => ['pt-PT' => 'Samoa',                             'en-UK' => 'Samoa']],
            ['iso_alpha2' => 'SM', 'country_code' => '+378',   'translations' => ['pt-PT' => 'São Marino',                        'en-UK' => 'San Marino']],
            ['iso_alpha2' => 'ST', 'country_code' => '+239',   'translations' => ['pt-PT' => 'São Tomé e Príncipe',               'en-UK' => 'Sao Tome and Principe']],
            ['iso_alpha2' => 'SA', 'country_code' => '+966',   'translations' => ['pt-PT' => 'Arábia Saudita',                    'en-UK' => 'Saudi Arabia']],
            ['iso_alpha2' => 'SN', 'country_code' => '+221',   'translations' => ['pt-PT' => 'Senegal',                           'en-UK' => 'Senegal']],
            ['iso_alpha2' => 'RS', 'country_code' => '+381',   'translations' => ['pt-PT' => 'Sérvia',                            'en-UK' => 'Serbia']],
            ['iso_alpha2' => 'SC', 'country_code' => '+248',   'translations' => ['pt-PT' => 'Seychelles',                        'en-UK' => 'Seychelles']],
            ['iso_alpha2' => 'SL', 'country_code' => '+232',   'translations' => ['pt-PT' => 'Serra Leoa',                        'en-UK' => 'Sierra Leone']],
            ['iso_alpha2' => 'SG', 'country_code' => '+65',    'translations' => ['pt-PT' => 'Singapura',                         'en-UK' => 'Singapore']],
            ['iso_alpha2' => 'SK', 'country_code' => '+421',   'translations' => ['pt-PT' => 'Eslováquia',                        'en-UK' => 'Slovakia']],
            ['iso_alpha2' => 'SI', 'country_code' => '+386',   'translations' => ['pt-PT' => 'Eslovénia',                         'en-UK' => 'Slovenia']],
            ['iso_alpha2' => 'SB', 'country_code' => '+677',   'translations' => ['pt-PT' => 'Ilhas Salomão',                     'en-UK' => 'Solomon Islands']],
            ['iso_alpha2' => 'SO', 'country_code' => '+252',   'translations' => ['pt-PT' => 'Somália',                           'en-UK' => 'Somalia']],
            ['iso_alpha2' => 'ZA', 'country_code' => '+27',    'translations' => ['pt-PT' => 'África do Sul',                     'en-UK' => 'South Africa']],
            ['iso_alpha2' => 'SS', 'country_code' => '+211',   'translations' => ['pt-PT' => 'Sudão do Sul',                      'en-UK' => 'South Sudan']],
            ['iso_alpha2' => 'ES', 'country_code' => '+34',    'translations' => ['pt-PT' => 'Espanha',                           'en-UK' => 'Spain']],
            ['iso_alpha2' => 'LK', 'country_code' => '+94',    'translations' => ['pt-PT' => 'Sri Lanka',                         'en-UK' => 'Sri Lanka']],
            ['iso_alpha2' => 'SD', 'country_code' => '+249',   'translations' => ['pt-PT' => 'Sudão',                             'en-UK' => 'Sudan']],
            ['iso_alpha2' => 'SR', 'country_code' => '+597',   'translations' => ['pt-PT' => 'Suriname',                          'en-UK' => 'Suriname']],
            ['iso_alpha2' => 'SE', 'country_code' => '+46',    'translations' => ['pt-PT' => 'Suécia',                            'en-UK' => 'Sweden']],
            ['iso_alpha2' => 'CH', 'country_code' => '+41',    'translations' => ['pt-PT' => 'Suíça',                             'en-UK' => 'Switzerland']],
            ['iso_alpha2' => 'SY', 'country_code' => '+963',   'translations' => ['pt-PT' => 'Síria',                             'en-UK' => 'Syria']],
            ['iso_alpha2' => 'TW', 'country_code' => '+886',   'translations' => ['pt-PT' => 'Taiwan',                            'en-UK' => 'Taiwan']],
            ['iso_alpha2' => 'TJ', 'country_code' => '+992',   'translations' => ['pt-PT' => 'Tajiquistão',                       'en-UK' => 'Tajikistan']],
            ['iso_alpha2' => 'TZ', 'country_code' => '+255',   'translations' => ['pt-PT' => 'Tanzânia',                          'en-UK' => 'Tanzania']],
            ['iso_alpha2' => 'TH', 'country_code' => '+66',    'translations' => ['pt-PT' => 'Tailândia',                         'en-UK' => 'Thailand']],
            ['iso_alpha2' => 'TL', 'country_code' => '+670',   'translations' => ['pt-PT' => 'Timor-Leste',                       'en-UK' => 'Timor-Leste']],
            ['iso_alpha2' => 'TG', 'country_code' => '+228',   'translations' => ['pt-PT' => 'Togo',                              'en-UK' => 'Togo']],
            ['iso_alpha2' => 'TO', 'country_code' => '+676',   'translations' => ['pt-PT' => 'Tonga',                             'en-UK' => 'Tonga']],
            ['iso_alpha2' => 'TT', 'country_code' => '+1-868', 'translations' => ['pt-PT' => 'Trinidad e Tobago',                 'en-UK' => 'Trinidad and Tobago']],
            ['iso_alpha2' => 'TN', 'country_code' => '+216',   'translations' => ['pt-PT' => 'Tunísia',                           'en-UK' => 'Tunisia']],
            ['iso_alpha2' => 'TR', 'country_code' => '+90',    'translations' => ['pt-PT' => 'Turquia',                           'en-UK' => 'Turkey']],
            ['iso_alpha2' => 'TM', 'country_code' => '+993',   'translations' => ['pt-PT' => 'Turquemenistão',                    'en-UK' => 'Turkmenistan']],
            ['iso_alpha2' => 'TV', 'country_code' => '+688',   'translations' => ['pt-PT' => 'Tuvalu',                            'en-UK' => 'Tuvalu']],
            ['iso_alpha2' => 'UG', 'country_code' => '+256',   'translations' => ['pt-PT' => 'Uganda',                            'en-UK' => 'Uganda']],
            ['iso_alpha2' => 'UA', 'country_code' => '+380',   'translations' => ['pt-PT' => 'Ucrânia',                           'en-UK' => 'Ukraine']],
            ['iso_alpha2' => 'AE', 'country_code' => '+971',   'translations' => ['pt-PT' => 'Emirados Árabes Unidos',            'en-UK' => 'United Arab Emirates']],
            ['iso_alpha2' => 'GB', 'country_code' => '+44',    'translations' => ['pt-PT' => 'Reino Unido',                       'en-UK' => 'United Kingdom']],
            ['iso_alpha2' => 'US', 'country_code' => '+1',     'translations' => ['pt-PT' => 'Estados Unidos',                    'en-UK' => 'United States']],
            ['iso_alpha2' => 'UY', 'country_code' => '+598',   'translations' => ['pt-PT' => 'Uruguai',                           'en-UK' => 'Uruguay']],
            ['iso_alpha2' => 'UZ', 'country_code' => '+998',   'translations' => ['pt-PT' => 'Uzbequistão',                       'en-UK' => 'Uzbekistan']],
            ['iso_alpha2' => 'VU', 'country_code' => '+678',   'translations' => ['pt-PT' => 'Vanuatu',                           'en-UK' => 'Vanuatu']],
            ['iso_alpha2' => 'VA', 'country_code' => '+379',   'translations' => ['pt-PT' => 'Vaticano',                          'en-UK' => 'Vatican City']],
            ['iso_alpha2' => 'VE', 'country_code' => '+58',    'translations' => ['pt-PT' => 'Venezuela',                         'en-UK' => 'Venezuela']],
            ['iso_alpha2' => 'VN', 'country_code' => '+84',    'translations' => ['pt-PT' => 'Vietname',                          'en-UK' => 'Vietnam']],
            ['iso_alpha2' => 'YE', 'country_code' => '+967',   'translations' => ['pt-PT' => 'Iémen',                             'en-UK' => 'Yemen']],
            ['iso_alpha2' => 'ZM', 'country_code' => '+260',   'translations' => ['pt-PT' => 'Zâmbia',                            'en-UK' => 'Zambia']],
            ['iso_alpha2' => 'ZW', 'country_code' => '+263',   'translations' => ['pt-PT' => 'Zimbabué',                          'en-UK' => 'Zimbabwe']],
        ];

        // Truncate and re-seed from scratch (disables FK checks temporarily)
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        CountryTranslation::truncate();
        Country::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        // Only seed the locales explicitly listed in each entry's 'translations' key.
        // Locales not present (e.g. es-ES) are intentionally left untouched.
        foreach ($countries as $data) {
            $country = Country::create([
                'iso_alpha2' => $data['iso_alpha2'],
                'country_code' => $data['country_code'],
                'is_active' => true,
            ]);

            foreach ($data['translations'] as $locale => $name) {
                CountryTranslation::create([
                    'country_id' => $country->id,
                    'locale' => $locale,
                    'name' => $name,
                ]);
            }
        }
    }
}
