<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['name_pt' => 'Afeganistão', 'name_en' => 'Afghanistan', 'iso_alpha2' => 'AF', 'country_code' => '+93'],
            ['name_pt' => 'Albânia', 'name_en' => 'Albania', 'iso_alpha2' => 'AL', 'country_code' => '+355'],
            ['name_pt' => 'Argélia', 'name_en' => 'Algeria', 'iso_alpha2' => 'DZ', 'country_code' => '+213'],
            ['name_pt' => 'Andorra', 'name_en' => 'Andorra', 'iso_alpha2' => 'AD', 'country_code' => '+376'],
            ['name_pt' => 'Angola', 'name_en' => 'Angola', 'iso_alpha2' => 'AO', 'country_code' => '+244'],
            ['name_pt' => 'Antígua e Barbuda', 'name_en' => 'Antigua and Barbuda', 'iso_alpha2' => 'AG', 'country_code' => '+1-268'],
            ['name_pt' => 'Argentina', 'name_en' => 'Argentina', 'iso_alpha2' => 'AR', 'country_code' => '+54'],
            ['name_pt' => 'Arménia', 'name_en' => 'Armenia', 'iso_alpha2' => 'AM', 'country_code' => '+374'],
            ['name_pt' => 'Austrália', 'name_en' => 'Australia', 'iso_alpha2' => 'AU', 'country_code' => '+61'],
            ['name_pt' => 'Áustria', 'name_en' => 'Austria', 'iso_alpha2' => 'AT', 'country_code' => '+43'],
            ['name_pt' => 'Azerbaijão', 'name_en' => 'Azerbaijan', 'iso_alpha2' => 'AZ', 'country_code' => '+994'],
            ['name_pt' => 'Bahamas', 'name_en' => 'Bahamas', 'iso_alpha2' => 'BS', 'country_code' => '+1-242'],
            ['name_pt' => 'Bahrein', 'name_en' => 'Bahrain', 'iso_alpha2' => 'BH', 'country_code' => '+973'],
            ['name_pt' => 'Bangladesh', 'name_en' => 'Bangladesh', 'iso_alpha2' => 'BD', 'country_code' => '+880'],
            ['name_pt' => 'Barbados', 'name_en' => 'Barbados', 'iso_alpha2' => 'BB', 'country_code' => '+1-246'],
            ['name_pt' => 'Bielorrússia', 'name_en' => 'Belarus', 'iso_alpha2' => 'BY', 'country_code' => '+375'],
            ['name_pt' => 'Bélgica', 'name_en' => 'Belgium', 'iso_alpha2' => 'BE', 'country_code' => '+32'],
            ['name_pt' => 'Belize', 'name_en' => 'Belize', 'iso_alpha2' => 'BZ', 'country_code' => '+501'],
            ['name_pt' => 'Benim', 'name_en' => 'Benin', 'iso_alpha2' => 'BJ', 'country_code' => '+229'],
            ['name_pt' => 'Butão', 'name_en' => 'Bhutan', 'iso_alpha2' => 'BT', 'country_code' => '+975'],
            ['name_pt' => 'Bolívia', 'name_en' => 'Bolivia', 'iso_alpha2' => 'BO', 'country_code' => '+591'],
            ['name_pt' => 'Bósnia e Herzegovina', 'name_en' => 'Bosnia and Herzegovina', 'iso_alpha2' => 'BA', 'country_code' => '+387'],
            ['name_pt' => 'Botswana', 'name_en' => 'Botswana', 'iso_alpha2' => 'BW', 'country_code' => '+267'],
            ['name_pt' => 'Brasil', 'name_en' => 'Brazil', 'iso_alpha2' => 'BR', 'country_code' => '+55'],
            ['name_pt' => 'Brunei', 'name_en' => 'Brunei', 'iso_alpha2' => 'BN', 'country_code' => '+673'],
            ['name_pt' => 'Bulgária', 'name_en' => 'Bulgaria', 'iso_alpha2' => 'BG', 'country_code' => '+359'],
            ['name_pt' => 'Burkina Faso', 'name_en' => 'Burkina Faso', 'iso_alpha2' => 'BF', 'country_code' => '+226'],
            ['name_pt' => 'Burundi', 'name_en' => 'Burundi', 'iso_alpha2' => 'BI', 'country_code' => '+257'],
            ['name_pt' => 'Cabo Verde', 'name_en' => 'Cabo Verde', 'iso_alpha2' => 'CV', 'country_code' => '+238'],
            ['name_pt' => 'Camboja', 'name_en' => 'Cambodia', 'iso_alpha2' => 'KH', 'country_code' => '+855'],
            ['name_pt' => 'Camarões', 'name_en' => 'Cameroon', 'iso_alpha2' => 'CM', 'country_code' => '+237'],
            ['name_pt' => 'Canadá', 'name_en' => 'Canada', 'iso_alpha2' => 'CA', 'country_code' => '+1'],
            ['name_pt' => 'República Centro-Africana', 'name_en' => 'Central African Republic', 'iso_alpha2' => 'CF', 'country_code' => '+236'],
            ['name_pt' => 'Chade', 'name_en' => 'Chad', 'iso_alpha2' => 'TD', 'country_code' => '+235'],
            ['name_pt' => 'Chile', 'name_en' => 'Chile', 'iso_alpha2' => 'CL', 'country_code' => '+56'],
            ['name_pt' => 'China', 'name_en' => 'China', 'iso_alpha2' => 'CN', 'country_code' => '+86'],
            ['name_pt' => 'Colômbia', 'name_en' => 'Colombia', 'iso_alpha2' => 'CO', 'country_code' => '+57'],
            ['name_pt' => 'Comores', 'name_en' => 'Comoros', 'iso_alpha2' => 'KM', 'country_code' => '+269'],
            ['name_pt' => 'Congo', 'name_en' => 'Congo', 'iso_alpha2' => 'CG', 'country_code' => '+242'],
            ['name_pt' => 'República Democrática do Congo', 'name_en' => 'Congo (DRC)', 'iso_alpha2' => 'CD', 'country_code' => '+243'],
            ['name_pt' => 'Costa Rica', 'name_en' => 'Costa Rica', 'iso_alpha2' => 'CR', 'country_code' => '+506'],
            ['name_pt' => 'Costa do Marfim', 'name_en' => 'Côte d\'Ivoire', 'iso_alpha2' => 'CI', 'country_code' => '+225'],
            ['name_pt' => 'Croácia', 'name_en' => 'Croatia', 'iso_alpha2' => 'HR', 'country_code' => '+385'],
            ['name_pt' => 'Cuba', 'name_en' => 'Cuba', 'iso_alpha2' => 'CU', 'country_code' => '+53'],
            ['name_pt' => 'Chipre', 'name_en' => 'Cyprus', 'iso_alpha2' => 'CY', 'country_code' => '+357'],
            ['name_pt' => 'Chéquia', 'name_en' => 'Czech Republic', 'iso_alpha2' => 'CZ', 'country_code' => '+420'],
            ['name_pt' => 'Dinamarca', 'name_en' => 'Denmark', 'iso_alpha2' => 'DK', 'country_code' => '+45'],
            ['name_pt' => 'Djibouti', 'name_en' => 'Djibouti', 'iso_alpha2' => 'DJ', 'country_code' => '+253'],
            ['name_pt' => 'Dominica', 'name_en' => 'Dominica', 'iso_alpha2' => 'DM', 'country_code' => '+1-767'],
            ['name_pt' => 'República Dominicana', 'name_en' => 'Dominican Republic', 'iso_alpha2' => 'DO', 'country_code' => '+1-809'],
            ['name_pt' => 'Equador', 'name_en' => 'Ecuador', 'iso_alpha2' => 'EC', 'country_code' => '+593'],
            ['name_pt' => 'Egito', 'name_en' => 'Egypt', 'iso_alpha2' => 'EG', 'country_code' => '+20'],
            ['name_pt' => 'El Salvador', 'name_en' => 'El Salvador', 'iso_alpha2' => 'SV', 'country_code' => '+503'],
            ['name_pt' => 'Guiné Equatorial', 'name_en' => 'Equatorial Guinea', 'iso_alpha2' => 'GQ', 'country_code' => '+240'],
            ['name_pt' => 'Eritreia', 'name_en' => 'Eritrea', 'iso_alpha2' => 'ER', 'country_code' => '+291'],
            ['name_pt' => 'Estónia', 'name_en' => 'Estonia', 'iso_alpha2' => 'EE', 'country_code' => '+372'],
            ['name_pt' => 'Eswatini', 'name_en' => 'Eswatini', 'iso_alpha2' => 'SZ', 'country_code' => '+268'],
            ['name_pt' => 'Etiópia', 'name_en' => 'Ethiopia', 'iso_alpha2' => 'ET', 'country_code' => '+251'],
            ['name_pt' => 'Fiji', 'name_en' => 'Fiji', 'iso_alpha2' => 'FJ', 'country_code' => '+679'],
            ['name_pt' => 'Finlândia', 'name_en' => 'Finland', 'iso_alpha2' => 'FI', 'country_code' => '+358'],
            ['name_pt' => 'França', 'name_en' => 'France', 'iso_alpha2' => 'FR', 'country_code' => '+33'],
            ['name_pt' => 'Gabão', 'name_en' => 'Gabon', 'iso_alpha2' => 'GA', 'country_code' => '+241'],
            ['name_pt' => 'Gâmbia', 'name_en' => 'Gambia', 'iso_alpha2' => 'GM', 'country_code' => '+220'],
            ['name_pt' => 'Geórgia', 'name_en' => 'Georgia', 'iso_alpha2' => 'GE', 'country_code' => '+995'],
            ['name_pt' => 'Alemanha', 'name_en' => 'Germany', 'iso_alpha2' => 'DE', 'country_code' => '+49'],
            ['name_pt' => 'Gana', 'name_en' => 'Ghana', 'iso_alpha2' => 'GH', 'country_code' => '+233'],
            ['name_pt' => 'Grécia', 'name_en' => 'Greece', 'iso_alpha2' => 'GR', 'country_code' => '+30'],
            ['name_pt' => 'Granada', 'name_en' => 'Grenada', 'iso_alpha2' => 'GD', 'country_code' => '+1-473'],
            ['name_pt' => 'Guatemala', 'name_en' => 'Guatemala', 'iso_alpha2' => 'GT', 'country_code' => '+502'],
            ['name_pt' => 'Guiné', 'name_en' => 'Guinea', 'iso_alpha2' => 'GN', 'country_code' => '+224'],
            ['name_pt' => 'Guiné-Bissau', 'name_en' => 'Guinea-Bissau', 'iso_alpha2' => 'GW', 'country_code' => '+245'],
            ['name_pt' => 'Guiana', 'name_en' => 'Guyana', 'iso_alpha2' => 'GY', 'country_code' => '+592'],
            ['name_pt' => 'Haiti', 'name_en' => 'Haiti', 'iso_alpha2' => 'HT', 'country_code' => '+509'],
            ['name_pt' => 'Honduras', 'name_en' => 'Honduras', 'iso_alpha2' => 'HN', 'country_code' => '+504'],
            ['name_pt' => 'Hungria', 'name_en' => 'Hungary', 'iso_alpha2' => 'HU', 'country_code' => '+36'],
            ['name_pt' => 'Islândia', 'name_en' => 'Iceland', 'iso_alpha2' => 'IS', 'country_code' => '+354'],
            ['name_pt' => 'Índia', 'name_en' => 'India', 'iso_alpha2' => 'IN', 'country_code' => '+91'],
            ['name_pt' => 'Indonésia', 'name_en' => 'Indonesia', 'iso_alpha2' => 'ID', 'country_code' => '+62'],
            ['name_pt' => 'Irão', 'name_en' => 'Iran', 'iso_alpha2' => 'IR', 'country_code' => '+98'],
            ['name_pt' => 'Iraque', 'name_en' => 'Iraq', 'iso_alpha2' => 'IQ', 'country_code' => '+964'],
            ['name_pt' => 'Irlanda', 'name_en' => 'Ireland', 'iso_alpha2' => 'IE', 'country_code' => '+353'],
            ['name_pt' => 'Israel', 'name_en' => 'Israel', 'iso_alpha2' => 'IL', 'country_code' => '+972'],
            ['name_pt' => 'Itália', 'name_en' => 'Italy', 'iso_alpha2' => 'IT', 'country_code' => '+39'],
            ['name_pt' => 'Jamaica', 'name_en' => 'Jamaica', 'iso_alpha2' => 'JM', 'country_code' => '+1-876'],
            ['name_pt' => 'Japão', 'name_en' => 'Japan', 'iso_alpha2' => 'JP', 'country_code' => '+81'],
            ['name_pt' => 'Jordânia', 'name_en' => 'Jordan', 'iso_alpha2' => 'JO', 'country_code' => '+962'],
            ['name_pt' => 'Cazaquistão', 'name_en' => 'Kazakhstan', 'iso_alpha2' => 'KZ', 'country_code' => '+7'],
            ['name_pt' => 'Quénia', 'name_en' => 'Kenya', 'iso_alpha2' => 'KE', 'country_code' => '+254'],
            ['name_pt' => 'Kiribati', 'name_en' => 'Kiribati', 'iso_alpha2' => 'KI', 'country_code' => '+686'],
            ['name_pt' => 'Coreia do Norte', 'name_en' => 'Korea (North)', 'iso_alpha2' => 'KP', 'country_code' => '+850'],
            ['name_pt' => 'Coreia do Sul', 'name_en' => 'Korea (South)', 'iso_alpha2' => 'KR', 'country_code' => '+82'],
            ['name_pt' => 'Kosovo', 'name_en' => 'Kosovo', 'iso_alpha2' => 'XK', 'country_code' => '+383'],
            ['name_pt' => 'Kuwait', 'name_en' => 'Kuwait', 'iso_alpha2' => 'KW', 'country_code' => '+965'],
            ['name_pt' => 'Quirguistão', 'name_en' => 'Kyrgyzstan', 'iso_alpha2' => 'KG', 'country_code' => '+996'],
            ['name_pt' => 'Laos', 'name_en' => 'Laos', 'iso_alpha2' => 'LA', 'country_code' => '+856'],
            ['name_pt' => 'Letónia', 'name_en' => 'Latvia', 'iso_alpha2' => 'LV', 'country_code' => '+371'],
            ['name_pt' => 'Líbano', 'name_en' => 'Lebanon', 'iso_alpha2' => 'LB', 'country_code' => '+961'],
            ['name_pt' => 'Lesoto', 'name_en' => 'Lesotho', 'iso_alpha2' => 'LS', 'country_code' => '+266'],
            ['name_pt' => 'Libéria', 'name_en' => 'Liberia', 'iso_alpha2' => 'LR', 'country_code' => '+231'],
            ['name_pt' => 'Líbia', 'name_en' => 'Libya', 'iso_alpha2' => 'LY', 'country_code' => '+218'],
            ['name_pt' => 'Liechtenstein', 'name_en' => 'Liechtenstein', 'iso_alpha2' => 'LI', 'country_code' => '+423'],
            ['name_pt' => 'Lituânia', 'name_en' => 'Lithuania', 'iso_alpha2' => 'LT', 'country_code' => '+370'],
            ['name_pt' => 'Luxemburgo', 'name_en' => 'Luxembourg', 'iso_alpha2' => 'LU', 'country_code' => '+352'],
            ['name_pt' => 'Madagáscar', 'name_en' => 'Madagascar', 'iso_alpha2' => 'MG', 'country_code' => '+261'],
            ['name_pt' => 'Malawi', 'name_en' => 'Malawi', 'iso_alpha2' => 'MW', 'country_code' => '+265'],
            ['name_pt' => 'Malásia', 'name_en' => 'Malaysia', 'iso_alpha2' => 'MY', 'country_code' => '+60'],
            ['name_pt' => 'Maldivas', 'name_en' => 'Maldives', 'iso_alpha2' => 'MV', 'country_code' => '+960'],
            ['name_pt' => 'Mali', 'name_en' => 'Mali', 'iso_alpha2' => 'ML', 'country_code' => '+223'],
            ['name_pt' => 'Malta', 'name_en' => 'Malta', 'iso_alpha2' => 'MT', 'country_code' => '+356'],
            ['name_pt' => 'Ilhas Marshall', 'name_en' => 'Marshall Islands', 'iso_alpha2' => 'MH', 'country_code' => '+692'],
            ['name_pt' => 'Mauritânia', 'name_en' => 'Mauritania', 'iso_alpha2' => 'MR', 'country_code' => '+222'],
            ['name_pt' => 'Maurícia', 'name_en' => 'Mauritius', 'iso_alpha2' => 'MU', 'country_code' => '+230'],
            ['name_pt' => 'México', 'name_en' => 'Mexico', 'iso_alpha2' => 'MX', 'country_code' => '+52'],
            ['name_pt' => 'Micronésia', 'name_en' => 'Micronesia', 'iso_alpha2' => 'FM', 'country_code' => '+691'],
            ['name_pt' => 'Moldávia', 'name_en' => 'Moldova', 'iso_alpha2' => 'MD', 'country_code' => '+373'],
            ['name_pt' => 'Mónaco', 'name_en' => 'Monaco', 'iso_alpha2' => 'MC', 'country_code' => '+377'],
            ['name_pt' => 'Mongólia', 'name_en' => 'Mongolia', 'iso_alpha2' => 'MN', 'country_code' => '+976'],
            ['name_pt' => 'Montenegro', 'name_en' => 'Montenegro', 'iso_alpha2' => 'ME', 'country_code' => '+382'],
            ['name_pt' => 'Marrocos', 'name_en' => 'Morocco', 'iso_alpha2' => 'MA', 'country_code' => '+212'],
            ['name_pt' => 'Moçambique', 'name_en' => 'Mozambique', 'iso_alpha2' => 'MZ', 'country_code' => '+258'],
            ['name_pt' => 'Myanmar', 'name_en' => 'Myanmar', 'iso_alpha2' => 'MM', 'country_code' => '+95'],
            ['name_pt' => 'Namíbia', 'name_en' => 'Namibia', 'iso_alpha2' => 'NA', 'country_code' => '+264'],
            ['name_pt' => 'Nauru', 'name_en' => 'Nauru', 'iso_alpha2' => 'NR', 'country_code' => '+674'],
            ['name_pt' => 'Nepal', 'name_en' => 'Nepal', 'iso_alpha2' => 'NP', 'country_code' => '+977'],
            ['name_pt' => 'Países Baixos', 'name_en' => 'Netherlands', 'iso_alpha2' => 'NL', 'country_code' => '+31'],
            ['name_pt' => 'Nova Zelândia', 'name_en' => 'New Zealand', 'iso_alpha2' => 'NZ', 'country_code' => '+64'],
            ['name_pt' => 'Nicarágua', 'name_en' => 'Nicaragua', 'iso_alpha2' => 'NI', 'country_code' => '+505'],
            ['name_pt' => 'Níger', 'name_en' => 'Niger', 'iso_alpha2' => 'NE', 'country_code' => '+227'],
            ['name_pt' => 'Nigéria', 'name_en' => 'Nigeria', 'iso_alpha2' => 'NG', 'country_code' => '+234'],
            ['name_pt' => 'Macedónia do Norte', 'name_en' => 'North Macedonia', 'iso_alpha2' => 'MK', 'country_code' => '+389'],
            ['name_pt' => 'Noruega', 'name_en' => 'Norway', 'iso_alpha2' => 'NO', 'country_code' => '+47'],
            ['name_pt' => 'Omã', 'name_en' => 'Oman', 'iso_alpha2' => 'OM', 'country_code' => '+968'],
            ['name_pt' => 'Paquistão', 'name_en' => 'Pakistan', 'iso_alpha2' => 'PK', 'country_code' => '+92'],
            ['name_pt' => 'Palau', 'name_en' => 'Palau', 'iso_alpha2' => 'PW', 'country_code' => '+680'],
            ['name_pt' => 'Palestina', 'name_en' => 'Palestine', 'iso_alpha2' => 'PS', 'country_code' => '+970'],
            ['name_pt' => 'Panamá', 'name_en' => 'Panama', 'iso_alpha2' => 'PA', 'country_code' => '+507'],
            ['name_pt' => 'Papua-Nova Guiné', 'name_en' => 'Papua New Guinea', 'iso_alpha2' => 'PG', 'country_code' => '+675'],
            ['name_pt' => 'Paraguai', 'name_en' => 'Paraguay', 'iso_alpha2' => 'PY', 'country_code' => '+595'],
            ['name_pt' => 'Peru', 'name_en' => 'Peru', 'iso_alpha2' => 'PE', 'country_code' => '+51'],
            ['name_pt' => 'Filipinas', 'name_en' => 'Philippines', 'iso_alpha2' => 'PH', 'country_code' => '+63'],
            ['name_pt' => 'Polónia', 'name_en' => 'Poland', 'iso_alpha2' => 'PL', 'country_code' => '+48'],
            ['name_pt' => 'Portugal', 'name_en' => 'Portugal', 'iso_alpha2' => 'PT', 'country_code' => '+351'],
            ['name_pt' => 'Qatar', 'name_en' => 'Qatar', 'iso_alpha2' => 'QA', 'country_code' => '+974'],
            ['name_pt' => 'Roménia', 'name_en' => 'Romania', 'iso_alpha2' => 'RO', 'country_code' => '+40'],
            ['name_pt' => 'Rússia', 'name_en' => 'Russia', 'iso_alpha2' => 'RU', 'country_code' => '+7'],
            ['name_pt' => 'Ruanda', 'name_en' => 'Rwanda', 'iso_alpha2' => 'RW', 'country_code' => '+250'],
            ['name_pt' => 'São Cristóvão e Neves', 'name_en' => 'Saint Kitts and Nevis', 'iso_alpha2' => 'KN', 'country_code' => '+1-869'],
            ['name_pt' => 'Santa Lúcia', 'name_en' => 'Saint Lucia', 'iso_alpha2' => 'LC', 'country_code' => '+1-758'],
            ['name_pt' => 'São Vicente e Granadinas', 'name_en' => 'Saint Vincent and the Grenadines', 'iso_alpha2' => 'VC', 'country_code' => '+1-784'],
            ['name_pt' => 'Samoa', 'name_en' => 'Samoa', 'iso_alpha2' => 'WS', 'country_code' => '+685'],
            ['name_pt' => 'São Marino', 'name_en' => 'San Marino', 'iso_alpha2' => 'SM', 'country_code' => '+378'],
            ['name_pt' => 'São Tomé e Príncipe', 'name_en' => 'Sao Tome and Principe', 'iso_alpha2' => 'ST', 'country_code' => '+239'],
            ['name_pt' => 'Arábia Saudita', 'name_en' => 'Saudi Arabia', 'iso_alpha2' => 'SA', 'country_code' => '+966'],
            ['name_pt' => 'Senegal', 'name_en' => 'Senegal', 'iso_alpha2' => 'SN', 'country_code' => '+221'],
            ['name_pt' => 'Sérvia', 'name_en' => 'Serbia', 'iso_alpha2' => 'RS', 'country_code' => '+381'],
            ['name_pt' => 'Seychelles', 'name_en' => 'Seychelles', 'iso_alpha2' => 'SC', 'country_code' => '+248'],
            ['name_pt' => 'Serra Leoa', 'name_en' => 'Sierra Leone', 'iso_alpha2' => 'SL', 'country_code' => '+232'],
            ['name_pt' => 'Singapura', 'name_en' => 'Singapore', 'iso_alpha2' => 'SG', 'country_code' => '+65'],
            ['name_pt' => 'Eslováquia', 'name_en' => 'Slovakia', 'iso_alpha2' => 'SK', 'country_code' => '+421'],
            ['name_pt' => 'Eslovénia', 'name_en' => 'Slovenia', 'iso_alpha2' => 'SI', 'country_code' => '+386'],
            ['name_pt' => 'Ilhas Salomão', 'name_en' => 'Solomon Islands', 'iso_alpha2' => 'SB', 'country_code' => '+677'],
            ['name_pt' => 'Somália', 'name_en' => 'Somalia', 'iso_alpha2' => 'SO', 'country_code' => '+252'],
            ['name_pt' => 'África do Sul', 'name_en' => 'South Africa', 'iso_alpha2' => 'ZA', 'country_code' => '+27'],
            ['name_pt' => 'Sudão do Sul', 'name_en' => 'South Sudan', 'iso_alpha2' => 'SS', 'country_code' => '+211'],
            ['name_pt' => 'Espanha', 'name_en' => 'Spain', 'iso_alpha2' => 'ES', 'country_code' => '+34'],
            ['name_pt' => 'Sri Lanka', 'name_en' => 'Sri Lanka', 'iso_alpha2' => 'LK', 'country_code' => '+94'],
            ['name_pt' => 'Sudão', 'name_en' => 'Sudan', 'iso_alpha2' => 'SD', 'country_code' => '+249'],
            ['name_pt' => 'Suriname', 'name_en' => 'Suriname', 'iso_alpha2' => 'SR', 'country_code' => '+597'],
            ['name_pt' => 'Suécia', 'name_en' => 'Sweden', 'iso_alpha2' => 'SE', 'country_code' => '+46'],
            ['name_pt' => 'Suíça', 'name_en' => 'Switzerland', 'iso_alpha2' => 'CH', 'country_code' => '+41'],
            ['name_pt' => 'Síria', 'name_en' => 'Syria', 'iso_alpha2' => 'SY', 'country_code' => '+963'],
            ['name_pt' => 'Taiwan', 'name_en' => 'Taiwan', 'iso_alpha2' => 'TW', 'country_code' => '+886'],
            ['name_pt' => 'Tajiquistão', 'name_en' => 'Tajikistan', 'iso_alpha2' => 'TJ', 'country_code' => '+992'],
            ['name_pt' => 'Tanzânia', 'name_en' => 'Tanzania', 'iso_alpha2' => 'TZ', 'country_code' => '+255'],
            ['name_pt' => 'Tailândia', 'name_en' => 'Thailand', 'iso_alpha2' => 'TH', 'country_code' => '+66'],
            ['name_pt' => 'Timor-Leste', 'name_en' => 'Timor-Leste', 'iso_alpha2' => 'TL', 'country_code' => '+670'],
            ['name_pt' => 'Togo', 'name_en' => 'Togo', 'iso_alpha2' => 'TG', 'country_code' => '+228'],
            ['name_pt' => 'Tonga', 'name_en' => 'Tonga', 'iso_alpha2' => 'TO', 'country_code' => '+676'],
            ['name_pt' => 'Trinidad e Tobago', 'name_en' => 'Trinidad and Tobago', 'iso_alpha2' => 'TT', 'country_code' => '+1-868'],
            ['name_pt' => 'Tunísia', 'name_en' => 'Tunisia', 'iso_alpha2' => 'TN', 'country_code' => '+216'],
            ['name_pt' => 'Turquia', 'name_en' => 'Turkey', 'iso_alpha2' => 'TR', 'country_code' => '+90'],
            ['name_pt' => 'Turquemenistão', 'name_en' => 'Turkmenistan', 'iso_alpha2' => 'TM', 'country_code' => '+993'],
            ['name_pt' => 'Tuvalu', 'name_en' => 'Tuvalu', 'iso_alpha2' => 'TV', 'country_code' => '+688'],
            ['name_pt' => 'Uganda', 'name_en' => 'Uganda', 'iso_alpha2' => 'UG', 'country_code' => '+256'],
            ['name_pt' => 'Ucrânia', 'name_en' => 'Ukraine', 'iso_alpha2' => 'UA', 'country_code' => '+380'],
            ['name_pt' => 'Emirados Árabes Unidos', 'name_en' => 'United Arab Emirates', 'iso_alpha2' => 'AE', 'country_code' => '+971'],
            ['name_pt' => 'Reino Unido', 'name_en' => 'United Kingdom', 'iso_alpha2' => 'GB', 'country_code' => '+44'],
            ['name_pt' => 'Estados Unidos', 'name_en' => 'United States', 'iso_alpha2' => 'US', 'country_code' => '+1'],
            ['name_pt' => 'Uruguai', 'name_en' => 'Uruguay', 'iso_alpha2' => 'UY', 'country_code' => '+598'],
            ['name_pt' => 'Uzbequistão', 'name_en' => 'Uzbekistan', 'iso_alpha2' => 'UZ', 'country_code' => '+998'],
            ['name_pt' => 'Vanuatu', 'name_en' => 'Vanuatu', 'iso_alpha2' => 'VU', 'country_code' => '+678'],
            ['name_pt' => 'Vaticano', 'name_en' => 'Vatican City', 'iso_alpha2' => 'VA', 'country_code' => '+379'],
            ['name_pt' => 'Venezuela', 'name_en' => 'Venezuela', 'iso_alpha2' => 'VE', 'country_code' => '+58'],
            ['name_pt' => 'Vietname', 'name_en' => 'Vietnam', 'iso_alpha2' => 'VN', 'country_code' => '+84'],
            ['name_pt' => 'Iémen', 'name_en' => 'Yemen', 'iso_alpha2' => 'YE', 'country_code' => '+967'],
            ['name_pt' => 'Zâmbia', 'name_en' => 'Zambia', 'iso_alpha2' => 'ZM', 'country_code' => '+260'],
            ['name_pt' => 'Zimbabué', 'name_en' => 'Zimbabwe', 'iso_alpha2' => 'ZW', 'country_code' => '+263'],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
