<?php

namespace Database\Seeders;

use App\Services\ImageThumbnailService;
use Illuminate\Database\Seeder;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('product_photos')->truncate();
        DB::table('category_product')->truncate();
        DB::table('material_product')->truncate();
        DB::table('product_translations')->truncate();
        DB::table('products')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('products')->insert([
            // twenty sample products – original first three items have been removed
            [
                'id' => 4,
                'uuid' => 'a1b2c3d4-e5f6-47ab-89cd-1234567890ab',
                'tax_id' => 1,
                'is_featured' => false,
                'is_promo' => true,
                'price' => '12.00',
                'promo_price' => '9.00',
                'width' => '50.00',
                'length' => '50.00',
                'height' => '60.00',
                'weight' => '120.000',
                'stock' => 25,
                'production_time' => 1,
                'is_backorder' => false,
                'active' => true,
                'created_at' => '2026-02-24 09:00:00',
                'updated_at' => '2026-02-24 09:00:00',
            ],
            [
                'id' => 5,
                'uuid' => 'b2c3d4e5-f6a7-48bc-90de-2345678901bc',
                'tax_id' => 1,
                'is_featured' => true,
                'is_promo' => false,
                'price' => '25.00',
                'promo_price' => '22.00',
                'width' => '200.00',
                'length' => '100.00',
                'height' => '150.00',
                'weight' => '300.000',
                'stock' => 5,
                'production_time' => 3,
                'is_backorder' => true,
                'active' => true,
                'created_at' => '2026-02-24 09:05:00',
                'updated_at' => '2026-02-24 09:05:00',
            ],
            [
                'id' => 6,
                'uuid' => 'c3d4e5f6-a7b8-49cd-01ef-3456789012cd',
                'tax_id' => 1,
                'is_featured' => false,
                'is_promo' => false,
                'price' => '7.50',
                'promo_price' => '7.50',
                'width' => '30.00',
                'length' => '30.00',
                'height' => '40.00',
                'weight' => '80.000',
                'stock' => 40,
                'production_time' => 1,
                'is_backorder' => false,
                'active' => true,
                'created_at' => '2026-02-24 09:10:00',
                'updated_at' => '2026-02-24 09:10:00',
            ],
            [
                'id' => 7,
                'uuid' => 'd4e5f6a7-b8c9-4aef-12f0-4567890123de',
                'tax_id' => 1,
                'is_featured' => true,
                'is_promo' => true,
                'price' => '18.00',
                'promo_price' => '15.00',
                'width' => '90.00',
                'length' => '90.00',
                'height' => '100.00',
                'weight' => '160.000',
                'stock' => 20,
                'production_time' => 2,
                'is_backorder' => true,
                'active' => true,
                'created_at' => '2026-02-24 09:15:00',
                'updated_at' => '2026-02-24 09:15:00',
            ],
            [
                'id' => 8,
                'uuid' => 'e5f6a7b8-c9d0-4bf1-23g1-5678901234ef',
                'tax_id' => 1,
                'is_featured' => false,
                'is_promo' => true,
                'price' => '5.00',
                'promo_price' => '4.00',
                'width' => '60.00',
                'length' => '60.00',
                'height' => '70.00',
                'weight' => '100.000',
                'stock' => 60,
                'production_time' => 1,
                'is_backorder' => false,
                'active' => true,
                'created_at' => '2026-02-24 09:20:00',
                'updated_at' => '2026-02-24 09:20:00',
            ],
            [
                'id' => 9,
                'uuid' => 'f6a7b8c9-d0e1-4cg2-34h2-6789012345f0',
                'tax_id' => 1,
                'is_featured' => true,
                'is_promo' => false,
                'price' => '30.00',
                'promo_price' => '30.00',
                'width' => '150.00',
                'length' => '150.00',
                'height' => '160.00',
                'weight' => '350.000',
                'stock' => 8,
                'production_time' => 4,
                'is_backorder' => true,
                'active' => true,
                'created_at' => '2026-02-24 09:25:00',
                'updated_at' => '2026-02-24 09:25:00',
            ],
            [
                'id' => 10,
                'uuid' => '01234567-89ab-4cd1-56ef-7890123456ab',
                'tax_id' => 1,
                'is_featured' => false,
                'is_promo' => true,
                'price' => '9.99',
                'promo_price' => '7.99',
                'width' => '45.00',
                'length' => '45.00',
                'height' => '55.00',
                'weight' => '90.000',
                'stock' => 30,
                'production_time' => 1,
                'is_backorder' => false,
                'active' => true,
                'created_at' => '2026-02-24 09:30:00',
                'updated_at' => '2026-02-24 09:30:00',
            ],
            [
                'id' => 11,
                'uuid' => '12345678-9abc-4de2-67f0-8901234567bc',
                'tax_id' => 1,
                'is_featured' => true,
                'is_promo' => false,
                'price' => '14.50',
                'promo_price' => '14.50',
                'width' => '70.00',
                'length' => '70.00',
                'height' => '80.00',
                'weight' => '130.000',
                'stock' => 18,
                'production_time' => 2,
                'is_backorder' => false,
                'active' => true,
                'created_at' => '2026-02-24 09:35:00',
                'updated_at' => '2026-02-24 09:35:00',
            ],
            [
                'id' => 12,
                'uuid' => '23456789-abcd-4ef3-78g1-9012345678cd',
                'tax_id' => 1,
                'is_featured' => false,
                'is_promo' => false,
                'price' => '6.00',
                'promo_price' => '5.00',
                'width' => '35.00',
                'length' => '35.00',
                'height' => '45.00',
                'weight' => '75.000',
                'stock' => 50,
                'production_time' => 1,
                'is_backorder' => false,
                'active' => true,
                'created_at' => '2026-02-24 09:40:00',
                'updated_at' => '2026-02-24 09:40:00',
            ],
            [
                'id' => 13,
                'uuid' => '34567890-bcde-4fg4-89h2-0123456789de',
                'tax_id' => 1,
                'is_featured' => true,
                'is_promo' => true,
                'price' => '22.00',
                'promo_price' => '18.00',
                'width' => '110.00',
                'length' => '110.00',
                'height' => '120.00',
                'weight' => '210.000',
                'stock' => 12,
                'production_time' => 3,
                'is_backorder' => true,
                'active' => true,
                'created_at' => '2026-02-24 09:45:00',
                'updated_at' => '2026-02-24 09:45:00',
            ],
            [
                'id' => 14,
                'uuid' => '45678901-cdef-4gh5-90i3-1234567890ef',
                'tax_id' => 1,
                'is_featured' => false,
                'is_promo' => true,
                'price' => '8.25',
                'promo_price' => '6.25',
                'width' => '55.00',
                'length' => '55.00',
                'height' => '65.00',
                'weight' => '95.000',
                'stock' => 28,
                'production_time' => 1,
                'is_backorder' => false,
                'active' => true,
                'created_at' => '2026-02-24 09:50:00',
                'updated_at' => '2026-02-24 09:50:00',
            ],
            [
                'id' => 15,
                'uuid' => '56789012-def0-4hi6-01j4-2345678901fa',
                'tax_id' => 1,
                'is_featured' => true,
                'is_promo' => false,
                'price' => '16.75',
                'promo_price' => '16.75',
                'width' => '85.00',
                'length' => '85.00',
                'height' => '95.00',
                'weight' => '150.000',
                'stock' => 22,
                'production_time' => 2,
                'is_backorder' => false,
                'active' => true,
                'created_at' => '2026-02-24 09:55:00',
                'updated_at' => '2026-02-24 09:55:00',
            ],
            [
                'id' => 16,
                'uuid' => '67890123-ef01-4ij7-12k5-3456789012ab',
                'tax_id' => 1,
                'is_featured' => false,
                'is_promo' => true,
                'price' => '4.50',
                'promo_price' => '3.50',
                'width' => '25.00',
                'length' => '25.00',
                'height' => '35.00',
                'weight' => '60.000',
                'stock' => 65,
                'production_time' => 1,
                'is_backorder' => false,
                'active' => true,
                'created_at' => '2026-02-24 10:00:00',
                'updated_at' => '2026-02-24 10:00:00',
            ],
            [
                'id' => 17,
                'uuid' => '78901234-f012-4jk8-23l6-4567890123bc',
                'tax_id' => 1,
                'is_featured' => true,
                'is_promo' => false,
                'price' => '28.00',
                'promo_price' => '28.00',
                'width' => '130.00',
                'length' => '130.00',
                'height' => '140.00',
                'weight' => '330.000',
                'stock' => 10,
                'production_time' => 4,
                'is_backorder' => true,
                'active' => true,
                'created_at' => '2026-02-24 10:05:00',
                'updated_at' => '2026-02-24 10:05:00',
            ],
            [
                'id' => 18,
                'uuid' => '89012345-0123-4kl9-34m7-5678901234cd',
                'tax_id' => 1,
                'is_featured' => false,
                'is_promo' => true,
                'price' => '11.00',
                'promo_price' => '9.00',
                'width' => '65.00',
                'length' => '65.00',
                'height' => '75.00',
                'weight' => '105.000',
                'stock' => 35,
                'production_time' => 1,
                'is_backorder' => false,
                'active' => true,
                'created_at' => '2026-02-24 10:10:00',
                'updated_at' => '2026-02-24 10:10:00',
            ],
            [
                'id' => 19,
                'uuid' => '90123456-1234-4lm0-45n8-6789012345de',
                'tax_id' => 1,
                'is_featured' => true,
                'is_promo' => false,
                'price' => '19.99',
                'promo_price' => '19.99',
                'width' => '95.00',
                'length' => '95.00',
                'height' => '105.00',
                'weight' => '170.000',
                'stock' => 24,
                'production_time' => 2,
                'is_backorder' => false,
                'active' => true,
                'created_at' => '2026-02-24 10:15:00',
                'updated_at' => '2026-02-24 10:15:00',
            ],
            [
                'id' => 20,
                'uuid' => '01234567-2345-4mn1-56o9-7890123456ef',
                'tax_id' => 1,
                'is_featured' => false,
                'is_promo' => true,
                'price' => '13.25',
                'promo_price' => '11.25',
                'width' => '75.00',
                'length' => '75.00',
                'height' => '85.00',
                'weight' => '125.000',
                'stock' => 27,
                'production_time' => 1,
                'is_backorder' => false,
                'active' => true,
                'created_at' => '2026-02-24 10:20:00',
                'updated_at' => '2026-02-24 10:20:00',
            ],
            [
                'id' => 21,
                'uuid' => '12345678-3456-4no2-67p0-8901234567fa',
                'tax_id' => 1,
                'is_featured' => true,
                'is_promo' => true,
                'price' => '17.00',
                'promo_price' => '14.00',
                'width' => '85.00',
                'length' => '85.00',
                'height' => '95.00',
                'weight' => '155.000',
                'stock' => 21,
                'production_time' => 2,
                'is_backorder' => false,
                'active' => true,
                'created_at' => '2026-02-24 10:25:00',
                'updated_at' => '2026-02-24 10:25:00',
            ],
            [
                'id' => 22,
                'uuid' => '23456789-4567-4op3-78q1-9012345678ab',
                'tax_id' => 1,
                'is_featured' => false,
                'is_promo' => false,
                'price' => '3.75',
                'promo_price' => '3.00',
                'width' => '20.00',
                'length' => '20.00',
                'height' => '30.00',
                'weight' => '50.000',
                'stock' => 80,
                'production_time' => 1,
                'is_backorder' => false,
                'active' => true,
                'created_at' => '2026-02-24 10:30:00',
                'updated_at' => '2026-02-24 10:30:00',
            ],
            [
                'id' => 23,
                'uuid' => '34567890-5678-4pq4-89r2-0123456789bc',
                'tax_id' => 1,
                'is_featured' => true,
                'is_promo' => false,
                'price' => '27.00',
                'promo_price' => '27.00',
                'width' => '125.00',
                'length' => '125.00',
                'height' => '135.00',
                'weight' => '310.000',
                'stock' => 9,
                'production_time' => 3,
                'is_backorder' => true,
                'active' => true,
                'created_at' => '2026-02-24 10:35:00',
                'updated_at' => '2026-02-24 10:35:00',
            ],
        ]);

        DB::table('product_translations')->insert([
            // realistic products aligned with categories
            ['id' => 7, 'product_id' => 4, 'locale' => 'pt-PT', 'name' => 'Ornamento Estrela de Natal',
                'description' => 'Estrela decorativa para pendurar na árvore de Natal.',
                'technical_info' => 'Feito em madeira pintada, 10cm de diâmetro.'],
            ['id' => 8, 'product_id' => 4, 'locale' => 'en-UK', 'name' => 'Christmas Star Ornament',
                'description' => 'Decorative star to hang on the Christmas tree.',
                'technical_info' => 'Wooden hand-painted, 10cm diameter.'],
            ['id' => 9, 'product_id' => 5, 'locale' => 'pt-PT', 'name' => 'Calendário de Advento de Madeira',
                'description' => 'Pequena caixa com 24 gavetas, uma para cada dia de dezembro.',
                'technical_info' => 'Madeira maciça com números gravados à mão.'],
            ['id' => 10, 'product_id' => 5, 'locale' => 'en-UK', 'name' => 'Wooden Advent Calendar',
                'description' => '24-drawer box, one for each December day.',
                'technical_info' => 'Solid wood with hand-etched numbers.'],
            ['id' => 11, 'product_id' => 6, 'locale' => 'pt-PT', 'name' => 'Suporte de Vela de Parede',
                'description' => 'Suporte fixado à parede para velas em copo.',
                'technical_info' => 'Ferro forjado, suporta vela de 6cm de diâmetro.'],
            ['id' => 12, 'product_id' => 6, 'locale' => 'en-UK', 'name' => 'Wall Candle Holder',
                'description' => 'Wall-mounted holder for glass candles.',
                'technical_info' => 'Forged iron, holds 6cm diameter candle.'],
            ['id' => 13, 'product_id' => 7, 'locale' => 'pt-PT', 'name' => 'Conjunto de 4 Posavasos Artesanais',
                'description' => 'Posavasos em cortiça com desenhos gravados.',
                'technical_info' => 'Cada par tem 10cm de diâmetro, impermeável.'],
            ['id' => 14, 'product_id' => 7, 'locale' => 'en-UK', 'name' => 'Handmade Coaster Set',
                'description' => 'Cork coasters with engraved patterns.',
                'technical_info' => '10cm diameter each, water-resistant.'],
            ['id' => 15, 'product_id' => 8, 'locale' => 'pt-PT', 'name' => 'Figura do Pai Natal',
                'description' => 'Figura decorativa de 20cm para estantes ou mesas.',
                'technical_info' => 'Resina pintada à mão, acabamento fosco.'],
            ['id' => 16, 'product_id' => 8, 'locale' => 'en-UK', 'name' => 'Santa Claus Figurine',
                'description' => '20cm decorative figurine for shelves or tables.',
                'technical_info' => 'Hand-painted resin, matte finish.'],
            ['id' => 17, 'product_id' => 9, 'locale' => 'pt-PT', 'name' => 'Organizador de Secretária com Gavetas',
                'description' => 'Pequeno organizador em madeira com três gavetas.',
                'technical_info' => 'Cada gaveta 8x8x5cm, puxadores metálicos.'],
            ['id' => 18, 'product_id' => 9, 'locale' => 'en-UK', 'name' => 'Desk Organizer with Drawers',
                'description' => 'Wooden desk organizer with three drawers.',
                'technical_info' => 'Drawers 8x8x5cm, metal handles.'],
            ['id' => 19, 'product_id' => 10, 'locale' => 'pt-PT', 'name' => 'Caminho de Mesa Bordado',
                'description' => 'Têxtil bordado à mão para decorar a mesa.',
                'technical_info' => '200x30cm, lavável à máquina em ciclo suave.'],
            ['id' => 20, 'product_id' => 10, 'locale' => 'en-UK', 'name' => 'Embroidered Table Runner',
                'description' => 'Hand-embroidered textile to adorn your table.',
                'technical_info' => '200x30cm, machine washable gentle cycle.'],
            ['id' => 21, 'product_id' => 11, 'locale' => 'pt-PT', 'name' => 'Caneca de Cerâmica Coleção Casa',
                'description' => "Caneca branca com impressão 'casa'.",
                'technical_info' => 'Capacidade 300ml, passou no teste de micro-ondas.'],
            ['id' => 22, 'product_id' => 11, 'locale' => 'en-UK', 'name' => 'Ceramic Mug – Home Collection',
                'description' => 'White mug printed with "Home".',
                'technical_info' => '300ml capacity, microwave safe.'],
            ['id' => 23, 'product_id' => 12, 'locale' => 'pt-PT', 'name' => 'Guirlanda de Feriado',
                'description' => 'Guirlanda verde com laços e pequenas bagas.',
                'technical_info' => 'Diâmetro 40cm, resistente ao exterior.'],
            ['id' => 24, 'product_id' => 12, 'locale' => 'en-UK', 'name' => 'Holiday Wreath',
                'description' => 'Green wreath with bows and small berries.',
                'technical_info' => '40cm diameter, weather-resistant.'],
            ['id' => 25, 'product_id' => 13, 'locale' => 'pt-PT', 'name' => 'Caixa de Arrumação de Brinquedos em Madeira',
                'description' => 'Caixa grande com tampa para guardar brinquedos.',
                'technical_info' => 'Madeira leve, 50x30x30cm, com alças laterais.'],
            ['id' => 26, 'product_id' => 13, 'locale' => 'en-UK', 'name' => 'Wooden Toy Storage Box',
                'description' => 'Large lidded box for toy storage.',
                'technical_info' => 'Lightweight wood, 50x30x30cm, side handles.'],
            ['id' => 27, 'product_id' => 14, 'locale' => 'pt-PT', 'name' => 'Lanterna Suspensa',
                'description' => 'Lanterna metálica para pendurar, com vela LED.',
                'technical_info' => '30cm altura, bateria AAA não incluída.'],
            ['id' => 28, 'product_id' => 14, 'locale' => 'en-UK', 'name' => 'Hanging Lantern',
                'description' => 'Metal lantern for hanging, includes LED candle.',
                'technical_info' => '30cm tall, requires AAA battery not included.'],
            ['id' => 29, 'product_id' => 15, 'locale' => 'pt-PT', 'name' => 'Suporte para Utensílios de Cozinha',
                'description' => 'Cilindro em inox para guardar colheres e espátulas.',
                'technical_info' => '11cm diâmetro, fácil de limpar.'],
            ['id' => 30, 'product_id' => 15, 'locale' => 'en-UK', 'name' => 'Kitchen Utensil Holder',
                'description' => 'Stainless steel cylinder for spoons and spatulas.',
                'technical_info' => '11cm diameter, easy to clean.'],
            ['id' => 31, 'product_id' => 16, 'locale' => 'pt-PT', 'name' => 'Pote de Luzes  de Fada',
                'description' => 'Frasco de vidro com cordão de 20 luzes LED.',
                'technical_info' => 'Usa 2 pilhas AA (não incluídas).'],
            ['id' => 32, 'product_id' => 16, 'locale' => 'en-UK', 'name' => 'Fairy Lights Mason Jar',
                'description' => 'Glass jar with string of 20 LED lights.',
                'technical_info' => 'Uses 2 AA batteries (not included).'],
            ['id' => 33, 'product_id' => 17, 'locale' => 'pt-PT', 'name' => 'Caderno de Couro',
                'description' => 'Caderno artesanal com capa em couro genuíno.',
                'technical_info' => 'A5, 100 folhas de papel reciclado.'],
            ['id' => 34, 'product_id' => 17, 'locale' => 'en-UK', 'name' => 'Leather Journal',
                'description' => 'Handmade journal with genuine leather cover.',
                'technical_info' => 'A5, 100 pages recycled paper.'],
            ['id' => 35, 'product_id' => 18, 'locale' => 'pt-PT', 'name' => 'Conjunto de Molduras para Fotos',
                'description' => 'Três molduras de madeira para fotografias 10x15cm.',
                'technical_info' => 'Resistentes a riscos, fundo de cartão.'],
            ['id' => 36, 'product_id' => 18, 'locale' => 'en-UK', 'name' => 'Picture Frame Set',
                'description' => 'Three wooden frames for 10x15cm photos.',
                'technical_info' => 'Scratch-resistant, cardboard back.'],
            ['id' => 37, 'product_id' => 19, 'locale' => 'pt-PT', 'name' => 'Espelho Emoldurado',
                'description' => 'Espelho retangular com moldura em madeira natural.',
                'technical_info' => '40x60cm, pendurado ou apoiado.'],
            ['id' => 38, 'product_id' => 19, 'locale' => 'en-UK', 'name' => 'Framed Mirror',
                'description' => 'Rectangular mirror with natural wood frame.',
                'technical_info' => '40x60cm, wall or tabletop mount.'],
            ['id' => 39, 'product_id' => 20, 'locale' => 'pt-PT', 'name' => 'Topo de Árvore de Natal',
                'description' => 'Topo em forma de anjo com detalhes em glitter.',
                'technical_info' => 'Altura 20cm, fácil de encaixar.'],
            ['id' => 40, 'product_id' => 20, 'locale' => 'en-UK', 'name' => 'Christmas Tree Topper',
                'description' => 'Angel-shaped topper with glitter details.',
                'technical_info' => '20cm tall, easy to attach.'],
            ['id' => 41, 'product_id' => 21, 'locale' => 'pt-PT', 'name' => 'Cesto Multiuso',
                'description' => 'Cesto trançado ideal para arrumar roupas ou brinquedos.',
                'technical_info' => '30x30x30cm, fibra natural.'],
            ['id' => 42, 'product_id' => 21, 'locale' => 'en-UK', 'name' => 'Multi-purpose Basket',
                'description' => 'Woven basket perfect for clothes or toys.',
                'technical_info' => '30x30x30cm, natural fiber.'],
            ['id' => 43, 'product_id' => 22, 'locale' => 'pt-PT', 'name' => 'Difusor Aromaterapia',
                'description' => 'Difusor elétrico para óleos essenciais.',
                'technical_info' => '200ml, desligamento automático.'],
            ['id' => 44, 'product_id' => 22, 'locale' => 'en-UK', 'name' => 'Aromatherapy Diffuser',
                'description' => 'Electric diffuser for essential oils.',
                'technical_info' => '200ml, auto shut-off.'],
            ['id' => 45, 'product_id' => 23, 'locale' => 'pt-PT', 'name' => 'Estante DIY',
                'description' => 'Estante modular em madeira para montagem fácil.',
                'technical_info' => '3 prateleiras, para parafusos inclusos.'],
            ['id' => 46, 'product_id' => 23, 'locale' => 'en-UK', 'name' => 'DIY Shelving Unit',
                'description' => 'Modular wooden shelving for easy assembly.',
                'technical_info' => '3 shelves, hardware included.'],
        ]);

        DB::table('category_product')->insert([
            // sample mappings for additional products
            ['product_id' => 4, 'category_id' => 1],
            ['product_id' => 5, 'category_id' => 1],
            ['product_id' => 5, 'category_id' => 3],
            ['product_id' => 6, 'category_id' => 2],
            ['product_id' => 7, 'category_id' => 4],
            ['product_id' => 8, 'category_id' => 1],
            ['product_id' => 9, 'category_id' => 3],
            ['product_id' => 10, 'category_id' => 2],
            ['product_id' => 11, 'category_id' => 4],
            ['product_id' => 12, 'category_id' => 1],
            ['product_id' => 13, 'category_id' => 3],
            ['product_id' => 14, 'category_id' => 2],
            ['product_id' => 15, 'category_id' => 4],
            ['product_id' => 16, 'category_id' => 1],
            ['product_id' => 17, 'category_id' => 3],
            ['product_id' => 18, 'category_id' => 2],
            ['product_id' => 19, 'category_id' => 4],
            ['product_id' => 20, 'category_id' => 1],
            ['product_id' => 21, 'category_id' => 3],
            ['product_id' => 22, 'category_id' => 2],
            ['product_id' => 23, 'category_id' => 4],
        ]);

        DB::table('material_product')->insert([
            // all additional products use the same sample material
            ['product_id' => 4, 'material_id' => 1],
            ['product_id' => 5, 'material_id' => 1],
            ['product_id' => 6, 'material_id' => 1],
            ['product_id' => 7, 'material_id' => 1],
            ['product_id' => 8, 'material_id' => 1],
            ['product_id' => 9, 'material_id' => 1],
            ['product_id' => 10, 'material_id' => 1],
            ['product_id' => 11, 'material_id' => 1],
            ['product_id' => 12, 'material_id' => 1],
            ['product_id' => 13, 'material_id' => 1],
            ['product_id' => 14, 'material_id' => 1],
            ['product_id' => 15, 'material_id' => 1],
            ['product_id' => 16, 'material_id' => 1],
            ['product_id' => 17, 'material_id' => 1],
            ['product_id' => 18, 'material_id' => 1],
            ['product_id' => 19, 'material_id' => 1],
            ['product_id' => 20, 'material_id' => 1],
            ['product_id' => 21, 'material_id' => 1],
            ['product_id' => 22, 'material_id' => 1],
            ['product_id' => 23, 'material_id' => 1],
        ]);

        // dynamically download representative photos for the retained products
        $service = new ImageThumbnailService;
        $unsplashService = app(\App\Services\UnsplashService::class);
        $queries = [
            // keep the same mapping as before – these IDs correspond to the 20 products we kept
            4 => 'christmas star ornament',
            5 => 'wooden advent calendar',
            6 => 'wall candle holder',
            7 => 'handmade coaster set',
            8 => 'santa claus figurine',
            9 => 'desk organizer with drawers',
            10 => 'embroidered table runner',
            11 => 'ceramic mug home',
            12 => 'holiday wreath',
            13 => 'wooden toy storage box',
            14 => 'hanging lantern',
            15 => 'kitchen utensil holder',
            16 => 'fairy lights mason jar',
            17 => 'leather journal',
            18 => 'picture frame set',
            19 => 'framed mirror',
            20 => 'christmas tree topper',
            21 => 'multi purpose basket',
            22 => 'aromatherapy diffuser',
            23 => 'diy shelving unit',
        ];

        $nextId = DB::table('product_photos')->max('id') + 1;
        $photoRows = [];
        $basePhotos = []; // will store the initial download rows for reuse

        // first pass: one photo per product, mark primary
        foreach ($queries as $pid => $query) {
            try {
                $downloaded = $unsplashService->searchAndDownload($query, 'seed-temp');
                if ($downloaded) {
                    $filePath = public_path($downloaded);
                    if (file_exists($filePath)) {
                        $file = new UploadedFile($filePath, basename($filePath), null, null, true);
                        $paths = $service->store($file, 'products');
                        $row = [
                            'id' => $nextId++,
                            'product_id' => $pid,
                            'path' => $paths['path'],
                            'original_path' => $paths['original_path'],
                            'is_primary' => 1,
                            'created_at' => now(),
                            'updated_at' => now(),
                        ];
                        $photoRows[] = $row;
                        $basePhotos[] = $row;
                        @unlink($filePath);
                    }
                }
            } catch (\Exception $e) {
                // ignore errors and continue
            }
        }

        // allocate additional photos by randomly reusing the downloaded set
        if (! empty($basePhotos)) {
            // start each product count at 1 (primary photo)
            $counts = array_fill_keys(array_keys($queries), 1);
            // continue until every product has at least 5 photos
            while (min($counts) < 5) {
                $eligible = array_filter($counts, function ($c) {
                    return $c < 5;
                });
                $targetPid = array_rand($eligible);
                $sample = $basePhotos[array_rand($basePhotos)];
                $photoRows[] = [
                    'id' => $nextId++,
                    'product_id' => $targetPid,
                    'path' => $sample['path'],
                    'original_path' => $sample['original_path'],
                    'is_primary' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
                $counts[$targetPid]++;
            }
        }

        // cleanup any leftover download cache
        @array_map('unlink', glob(public_path('seed-temp/*')));

        if (! empty($photoRows)) {
            DB::table('product_photos')->insert($photoRows);
        }
    }
}
